USE [hoahauhoanvu_com]
GO

/****** Object:  Table [dbo].[ESHOP_ALBUM_ITEM]    Script Date: 02/03/2015 11:36:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESHOP_ALBUM](
	[ALBUM_ID] [int] IDENTITY(1,1) NOT NULL,
	[ALBUM_NAME] [nvarchar](500) NULL,
	[ALBUM_DESC] [nvarchar](500) NULL,
	[ALBUM_ORDER] [int] NULL,
	[ALBUM_ACTIVE] [smallint] NULL,
	[ALBUM_TYPE] [int] NULL,
	[ALBUM_LANGUAGE] [int] NULL,
	[ALBUM_IMAGE1] [nvarchar](500) NULL,
	[ALBUM_IMAGE2] [nvarchar](500) NULL,
	[ALBUM_FIELD1] [nvarchar](500) NULL,
	[ALBUM_FIELD2] [nvarchar](500) NULL,
	[ALBUM_FIELD3] [nvarchar](500) NULL,
	[ALBUM_FIELD4] [nvarchar](500) NULL,
	[ALBUM_FIELD5] [nvarchar](500) NULL,
	[NEWS_ID] [int] NULL,
 CONSTRAINT [PK_ESHOP_ALBUM] PRIMARY KEY CLUSTERED 
(
	[ALBUM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ESHOP_ALBUM]  WITH CHECK ADD  CONSTRAINT [FK_ESHOP_ALBUM_ESHOP_NEWS] FOREIGN KEY([NEWS_ID])
REFERENCES [dbo].[ESHOP_NEWS] ([NEWS_ID])
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] CHECK CONSTRAINT [FK_ESHOP_ALBUM_ESHOP_NEWS]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_ESHOP_ALBUM_ALBUM_NAME]  DEFAULT ('') FOR [ALBUM_NAME]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_ESHOP_ALBUM_ALBUM_DESC]  DEFAULT ('') FOR [ALBUM_DESC]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_ESHOP_ALBUM_ALBUM_ORDER]  DEFAULT ((1)) FOR [ALBUM_ORDER]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_ESHOP_ALBUM_ALBUM_ACTIVE]  DEFAULT ((0)) FOR [ALBUM_ACTIVE]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_Table_1_ALBUM_ITEMTYPE]  DEFAULT ((0)) FOR [ALBUM_TYPE]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_ESHOP_ALBUM_ALBUM_FIELD1]  DEFAULT ('') FOR [ALBUM_FIELD1]
GO

ALTER TABLE [dbo].[ESHOP_ALBUM] ADD  CONSTRAINT [DF_ESHOP_ALBUM_ALBUM_FIELD2]  DEFAULT ('') FOR [ALBUM_FIELD2]
GO


CREATE TABLE [dbo].[ESHOP_ALBUM_ITEM](
	[ALBUM_ITEM_ID] [int] IDENTITY(1,1) NOT NULL,
	[ALBUM_ITEM_DESC] [nvarchar](1000) NULL,
	[ALBUM_ITEM_IMAGE1] [nvarchar](400) NULL,
	[ALBUM_ITEM_IMAGE2] [nvarchar](400) NULL,
	[ALBUM_ITEM_IMAGE3] [nvarchar](400) NULL,
	[ALBUM_ITEM_URL] [nchar](200) NULL,
	[ALBUM_ITEM_AUTOPLAY] [int] NULL,
	[ALBUM_ITEM_PERIOD] [int] NULL,
	[ALBUM_ITEM_ORDER] [nvarchar](400) NULL,
	[ALBUM_ITEM_TYPE] [int] NULL,
	[ALBUM_ITEM_FIELD1] [nvarchar](400) NULL,
	[ALBUM_ITEM_FIELD2] [nvarchar](400) NULL,
	[ALBUM_ITEM_FIELD3] [nvarchar](400) NULL,
	[ALBUM_ITEM_FIELD4] [nvarchar](400) NULL,
	[ALBUM_ITEM_FIELD5] [nvarchar](400) NULL,
	[ALBUM_ID] [int] NULL,
 CONSTRAINT [PK_ESHOP_ALBUM_ITEM] PRIMARY KEY CLUSTERED 
(
	[ALBUM_ITEM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ESHOP_ALBUM_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ESHOP_ALBUM_ITEM_ESHOP_ALBUM] FOREIGN KEY([ALBUM_ID])
REFERENCES [dbo].[ESHOP_ALBUM] ([ALBUM_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ESHOP_ALBUM_ITEM] CHECK CONSTRAINT [FK_ESHOP_ALBUM_ITEM_ESHOP_ALBUM]
GO


